[project]
name = "pre-commit-showcase"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "ipykernel>=6.29.5",
  "ipywidgets>=8.1.5",
  "matplotlib>=3.10.0",
  "mypy>=1.15.0",
  "pandas>=2.2.3",
]

[dependency-groups]
dev = ["pre-commit>=4.1.0"]
